spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pg_stream
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.generate_statistics: true
      hibernate.connection.driver_class: org.postgresql.driver

  flyway:
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    default-schema: dev
